<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net10.0</TargetFramework>
		<IsPackable>false</IsPackable>
		<NoWarn>CS1591</NoWarn>
	</PropertyGroup>

	<ItemGroup>
		<Compile Remove="BenchmarkDotNet.Artifacts\**" />
		<EmbeddedResource Remove="BenchmarkDotNet.Artifacts\**" />
		<None Remove="BenchmarkDotNet.Artifacts\**" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="BenchmarkDotNet" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\src\Umbrella.DynamicImage.Abstractions\Umbrella.DynamicImage.Abstractions.csproj" />
		<ProjectReference Include="..\..\src\Umbrella.DynamicImage.FreeImage\Umbrella.DynamicImage.FreeImage.csproj" />
		<ProjectReference Include="..\..\src\Umbrella.DynamicImage.NetVips\Umbrella.DynamicImage.NetVips.csproj" />
		<ProjectReference Include="..\..\src\Umbrella.DynamicImage.SkiaSharp\Umbrella.DynamicImage.SkiaSharp.csproj" />
	</ItemGroup>
	<ItemGroup>
		<None Update="Fixtures\*.jpg;Fixtures\*.png" CopyToOutputDirectory="PreserveNewest" />
	</ItemGroup>

</Project>
