using CommunityToolkit.Diagnostics;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Razor.TagHelpers;
using Microsoft.Extensions.Caching.Memory;
using Microsoft.Extensions.Logging;
using Umbrella.AspNetCore.WebUtilities.DynamicImage.Mvc.TagHelpers.Options;
using Umbrella.DynamicImage.Abstractions;
using Umbrella.Utilities.Caching.Abstractions;
using Umbrella.Utilities.Imaging.Abstractions;
using Umbrella.WebUtilities.Hosting;

namespace Umbrella.AspNetCore.WebUtilities.DynamicImage.Mvc.TagHelpers;

/// <summary>
/// A tag helper used to contribute art directed source tags to the picture element generated by a parent <see cref="DynamicImageTagHelper"/>.
/// </summary>
/// <remarks>
/// <para>
/// This must be nested inside a <c>dynamic-image</c> element. Each usage generates one source tag per configured
/// <see cref="DynamicImageTagHelperOptions.PictureSourceFormats"/> value together with a final source tag using its own
/// <see cref="DynamicImageTagHelperBase.ImageFormat"/>. The own-format source is required because a browser that has matched a media
/// condition will not fall back to the img element when it does not support any of the formats offered for that condition.
/// </para>
/// <para>
/// Any attribute that is not explicitly declared is inherited from the parent <c>dynamic-image</c> element.
/// </para>
/// </remarks>
/// <seealso cref="DynamicImageTagHelperBase" />
[OutputElementHint("source")]
[HtmlTargetElement("dynamic-source", Attributes = ChildRequiredAttributeNames, TagStructure = TagStructure.WithoutEndTag)]
public class DynamicImagePictureSourceTagHelper : DynamicImageTagHelperBase
{
	/// <summary>
	/// The required attribute names. Unlike the parent element, <c>src</c> is not required because it is inherited when it is not declared.
	/// </summary>
	protected const string ChildRequiredAttributeNames = WidthRequestAttributeName + "," + HeightRequestAttributeName;

	/// <summary>
	/// The media attribute name.
	/// </summary>
	protected const string MediaAttributeName = "media";

	/// <summary>
	/// Gets the name of the output tag.
	/// </summary>
	protected override string OutputTagName => "source";

	/// <summary>
	/// Gets or sets the media condition that the generated source tags apply to, e.g. <c>(max-width: 599px)</c>.
	/// </summary>
	[HtmlAttributeName(MediaAttributeName)]
	public string? Media { get; set; }

	/// <summary>
	/// Initializes a new instance of the <see cref="DynamicImagePictureSourceTagHelper"/> class.
	/// </summary>
	/// <param name="logger">The logger.</param>
	/// <param name="cache">The cache.</param>
	/// <param name="cacheKeyUtility">The cache key utility.</param>
	/// <param name="responsiveImageHelper">The responsive image helper.</param>
	/// <param name="dynamicImageUtility">The dynamic image utility.</param>
	/// <param name="umbrellaHostingEnvironment">The umbrella hosting environment.</param>
	/// <param name="dynamicImageTagHelperOptions">The dynamic image tag helper options.</param>
	public DynamicImagePictureSourceTagHelper(
		ILogger<DynamicImagePictureSourceTagHelper> logger,
		IUmbrellaWebHostingEnvironment umbrellaHostingEnvironment,
		IMemoryCache cache,
		ICacheKeyUtility cacheKeyUtility,
		IResponsiveImageHelper responsiveImageHelper,
		IDynamicImageUtility dynamicImageUtility,
		DynamicImageTagHelperOptions dynamicImageTagHelperOptions)
		: base(logger, umbrellaHostingEnvironment, cache, cacheKeyUtility, responsiveImageHelper, dynamicImageUtility, dynamicImageTagHelperOptions)
	{
	}

	/// <summary>
	/// Asynchronously executes the <see cref="TagHelper"/> with the given <paramref name="context"/> and <paramref name="output"/>.
	/// </summary>
	/// <param name="context">Contains information associated with the current HTML tag.</param>
	/// <param name="output">A stateful HTML element used to generate an HTML tag.</param>
	/// <returns>A <see cref="Task"/> that on completion updates the output.</returns>
	public override Task ProcessAsync(TagHelperContext context, TagHelperOutput output)
	{
		Guard.IsNotNull(context);
		Guard.IsNotNull(output);

		if (!context.Items.TryGetValue(typeof(DynamicImagePictureContext), out object? item) || item is not DynamicImagePictureContext pictureContext)
			throw new InvalidOperationException("A <dynamic-source> element can only be used inside a <dynamic-image> element.");

		// Checked before any URL is generated. The parent cannot report this until its child content has already run, by which point a
		// source inheriting the absolute URL would have generated and cached meaningless Dynamic Image URLs from it.
		if (pictureContext.IsExternalUrl)
			throw new InvalidOperationException("A <dynamic-source> element cannot be used inside a <dynamic-image> element that refers to an external URL.");

		if (string.IsNullOrWhiteSpace(Media))
			throw new InvalidOperationException($"A value for the {MediaAttributeName} attribute must be provided on a <dynamic-source> element.");

		string sourcePath = ApplyInheritedValues(context, pictureContext);

		ValidateSizeRequests();
		ValidateFocalPoint();

		// The formats are ordered most to least preferred with the fallback format last. Once the media condition of these sources has
		// been matched the browser will not fall back to the img element, so the fallback format has to be offered here as well.
		foreach (DynamicImageFormat format in DynamicImageTagHelperOptions.PictureSourceFormats.Where(x => x != ImageFormat).Append(ImageFormat))
		{
			TagBuilder source = BuildSourceTag(sourcePath, format, Media);
			AppendPassthroughAttributes(output, source);
			pictureContext.Sources.Add(source);
		}

		output.SuppressOutput();

		return Task.CompletedTask;
	}

	/// <summary>
	/// Applies the values of the parent <c>dynamic-image</c> element for every attribute that has not been explicitly declared on this
	/// element and returns the source path to generate URLs from.
	/// </summary>
	/// <param name="context">Contains information associated with the current HTML tag.</param>
	/// <param name="pictureContext">The state shared with the parent element.</param>
	/// <returns>The source path with the configured prefix removed.</returns>
	private string ApplyInheritedValues(TagHelperContext context, DynamicImagePictureContext pictureContext)
	{
		// TagHelperContext.AllAttributes contains exactly the attributes present in the Razor source, which is what allows an explicitly
		// declared value to be told apart from a property that is simply sitting at its default.
		bool IsDeclared(string name) => context.AllAttributes.ContainsName(name);

		string sourcePath = IsDeclared("src")
			? ResolveSourcePath(context.AllAttributes["src"]?.Value?.ToString())
			: pictureContext.SourcePath;

		if (!IsDeclared(VersionTokenAttributeName))
			VersionToken = pictureContext.VersionToken;

		if (!IsDeclared("resize-mode"))
			ResizeMode = pictureContext.ResizeMode;

		if (!IsDeclared("image-format"))
			ImageFormat = pictureContext.ImageFormat;

		if (!IsDeclared("filter-quality"))
			FilterQuality = pictureContext.FilterQuality;

		if (!IsDeclared("quality-request"))
			QualityRequest = pictureContext.QualityRequest;

		if (!IsDeclared(MaxPixelDensityAttributeName))
			ImageMaxPixelDensity = pictureContext.MaxPixelDensity;

		if (!IsDeclared(SizeWidthsAttributeName))
			SizeWidths = pictureContext.SizeWidths;

		// A focal point is only meaningful for the CropFocalPoint resize mode, so it is only inherited when the effective resize mode
		// still calls for one. Without this, declaring a different resize mode on a child of a focal point parent would throw.
		if (ResizeMode is DynamicResizeMode.CropFocalPoint)
		{
			if (!IsDeclared("focal-point-x"))
				FocalPointX = pictureContext.FocalPointX;

			if (!IsDeclared("focal-point-y"))
				FocalPointY = pictureContext.FocalPointY;
		}

		return sourcePath;
	}

	/// <summary>
	/// The attributes that are never copied onto a generated source tag.
	/// </summary>
	/// <remarks>
	/// <c>src</c> and <c>alt</c> are meaningless on a source tag, <c>srcset</c> and <c>type</c> are always generated, and <c>id</c> is
	/// excluded because a single element generates several source tags and repeating an id would produce invalid HTML.
	/// </remarks>
	private static readonly HashSet<string> _nonPassthroughAttributeNames = new(StringComparer.OrdinalIgnoreCase)
	{
		"src",
		"alt",
		"srcset",
		"type",
		"id"
	};

	/// <summary>
	/// Copies any attribute that is not bound to a tag helper property onto the generated source tag, e.g. <c>sizes</c> and <c>class</c>.
	/// </summary>
	/// <param name="output">A stateful HTML element used to generate an HTML tag.</param>
	/// <param name="source">The generated source tag.</param>
	private static void AppendPassthroughAttributes(TagHelperOutput output, TagBuilder source)
	{
		foreach (TagHelperAttribute attribute in output.Attributes)
		{
			if (_nonPassthroughAttributeNames.Contains(attribute.Name))
				continue;

			source.Attributes[attribute.Name] = attribute.Value?.ToString() ?? string.Empty;
		}
	}
}
