<Project>

	<PropertyGroup Condition="'$(IsTestProject)'=='true'">
		<OutputType>Exe</OutputType>
		<IsPackable>false</IsPackable>
		<NoWarn>$(NoWarn);CS1591</NoWarn>
		<WarningsAsErrors>$(WarningsAsErrors);xUnit1051</WarningsAsErrors>
		<PreserveCompilationContext>true</PreserveCompilationContext>
		<UseMicrosoftTestingPlatformRunner>true</UseMicrosoftTestingPlatformRunner>
	</PropertyGroup>

</Project>
