<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<IsTestProject>true</IsTestProject>
		<UserSecretsId>bc0ff87b-21dd-4f67-9fb7-a1e58161fc46</UserSecretsId>
	</PropertyGroup>

	<ItemGroup>
	  <ProjectReference Include="..\..\..\Internal\src\Umbrella.Internal.Mocks\Umbrella.Internal.Mocks.csproj" />
	  <ProjectReference Include="..\..\src\Umbrella.AzureServiceBus\Umbrella.AzureServiceBus.csproj" />
	</ItemGroup>

</Project>
