<Project>

	<PropertyGroup>
		<EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
		<EnableNETAnalyzers>true</EnableNETAnalyzers>
		<AnalysisMode>AllEnabledByDefault</AnalysisMode>
		<AnalysisLevel>latest</AnalysisLevel>
		<RunAnalyzersDuringBuild>true</RunAnalyzersDuringBuild>
		<RunAnalyzersDuringLiveAnalysis>true</RunAnalyzersDuringLiveAnalysis>
		<CodeAnalysisTreatWarningsAsErrors>false</CodeAnalysisTreatWarningsAsErrors>
		<TreatWarningsAsErrors>false</TreatWarningsAsErrors>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<NoWarn>CS1591</NoWarn>
		<!-- Mitigation for intermittent issues with Hot Reload -->
		<EnableSourceControlManagerQueries>true</EnableSourceControlManagerQueries>
	</PropertyGroup>

</Project>
