<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>netstandard2.0;net462;net8.0;net9.0;net10.0</TargetFrameworks>
	</PropertyGroup>

	<PropertyGroup>
		<PackageId>Umbrella.Utilities</PackageId>
		<Description>This package contains a range of utility classes to aid application development.</Description>
	</PropertyGroup>

	<ItemGroup>
	  <Compile Remove="Data\Options\**" />
	  <EmbeddedResource Remove="Data\Options\**" />
	  <None Remove="Data\Options\**" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="CommunityToolkit.Diagnostics" />
		<PackageReference Include="CommunityToolkit.HighPerformance" />
		<PackageReference Include="Humanizer.Core" />
		<PackageReference Include="ncrontab" />
		<PackageReference Include="Polly.Contrib.WaitAndRetry" />
	</ItemGroup>

	<ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.0' Or '$(TargetFramework)' == 'net462'">
		<PackageReference Include="System.Buffers" />
		<PackageReference Include="System.ComponentModel.Annotations" />
		<PackageReference Include="System.Runtime.Loader" />
		<PackageReference Include="System.Net.Http.Json" />
	</ItemGroup>

	<ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.0' Or '$(TargetFramework)' == 'net462'">
		<PackageReference Include="Microsoft.Extensions.Caching.Abstractions" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
		<PackageReference Include="Microsoft.Extensions.FileProviders.Physical" />
		<PackageReference Include="Microsoft.Extensions.Hosting" />
		<PackageReference Include="Microsoft.Extensions.Http" />
		<PackageReference Include="Microsoft.Extensions.Http.Polly" />
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
		<PackageReference Include="Microsoft.Extensions.ObjectPool" />
		<PackageReference Include="System.Text.Json" />
	</ItemGroup>

	<ItemGroup Condition="'$(TargetFramework)' == 'net8.0'">
		<PackageReference Include="Microsoft.Extensions.Caching.Abstractions" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
		<PackageReference Include="Microsoft.Extensions.FileProviders.Abstractions" />
		<PackageReference Include="Microsoft.Extensions.FileProviders.Physical" />
		<PackageReference Include="Microsoft.Extensions.Hosting" />
		<PackageReference Include="Microsoft.Extensions.Http" />
		<PackageReference Include="Microsoft.Extensions.Http.Polly" />
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
		<PackageReference Include="Microsoft.Extensions.ObjectPool" />
	</ItemGroup>

	<ItemGroup Condition="'$(TargetFramework)' == 'net9.0'">
		<PackageReference Include="Microsoft.Extensions.Caching.Abstractions" />
		<PackageReference Include="Microsoft.Extensions.Caching.Hybrid" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
		<PackageReference Include="Microsoft.Extensions.FileProviders.Abstractions" />
		<PackageReference Include="Microsoft.Extensions.FileProviders.Physical" />
		<PackageReference Include="Microsoft.Extensions.Hosting" />
		<PackageReference Include="Microsoft.Extensions.Http" />
		<PackageReference Include="Microsoft.Extensions.Http.Polly" />
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
		<PackageReference Include="Microsoft.Extensions.ObjectPool" />
	</ItemGroup>
	
	<ItemGroup Condition="'$(TargetFramework)' == 'net10.0'">
		<PackageReference Include="Microsoft.Extensions.Caching.Abstractions" />
		<PackageReference Include="Microsoft.Extensions.Caching.Hybrid" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
		<PackageReference Include="Microsoft.Extensions.FileProviders.Abstractions" />
		<PackageReference Include="Microsoft.Extensions.FileProviders.Physical" />
		<PackageReference Include="Microsoft.Extensions.Hosting" />
		<PackageReference Include="Microsoft.Extensions.Http" />
		<PackageReference Include="Microsoft.Extensions.Http.Polly" />
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
		<PackageReference Include="Microsoft.Extensions.ObjectPool" />
	</ItemGroup>

	<ItemGroup>
		<Content Include="..\..\..\icon.png" Pack="true" PackagePath="\" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Umbrella.DataAnnotations\Umbrella.DataAnnotations.csproj" />
	</ItemGroup>

</Project>
