using CommunityToolkit.Diagnostics;
using Microsoft.Extensions.Logging;
using Umbrella.Utilities.Exceptions;
using Umbrella.Utilities.Mapping.Abstractions;

namespace Umbrella.Utilities.Mapping.Mapperly;

/// <summary>
/// A very basic implementation of the <see cref="IUmbrellaMapper"/> which uses mapping classes partially generated by the Mapperly source generators internally.
/// </summary>
/// <seealso cref="IUmbrellaMapper" />
public class UmbrellaMapper : IUmbrellaMapper
{
	private readonly ILogger _logger;
	private readonly IServiceProvider _serviceProvider;
	private readonly UmbrellaMapperRegistry _registry;

	/// <summary>
	/// Initializes a new instance of the <see cref="UmbrellaMapper"/> class.
	/// </summary>
	/// <param name="logger">The logger.</param>
	/// <param name="serviceProvider">The service provider.</param>
	/// <param name="registry">The generated mapping registry.</param>
	internal UmbrellaMapper(
		ILogger<UmbrellaMapper> logger,
		IServiceProvider serviceProvider,
		UmbrellaMapperRegistry registry)
	{
		Guard.IsNotNull(logger);
		Guard.IsNotNull(serviceProvider);
		_logger = logger;
		_serviceProvider = serviceProvider;
		_registry = registry;
	}

	public async ValueTask<TDestination> MapAsync<TSource, TDestination>(TSource source, CancellationToken cancellationToken = default)
	{
		cancellationToken.ThrowIfCancellationRequested();
		Guard.IsNotNull(source);

		try
		{
			if (_registry.TryMapNewInstanceExact(_serviceProvider, source, cancellationToken, out ValueTask<TDestination> exactResult))
				return await exactResult.ConfigureAwait(false);

			if (source is System.Collections.IEnumerable and not string)
			{
				throw new InvalidOperationException(
					$"The source type is {source.GetType().FullName} which is a collection. Please call the {nameof(MapAllAsync)} methods to map collections.");
			}

			throw new InvalidOperationException(
				$"A mapper implementation for the specified source type {typeof(TSource).FullName} and destination type {typeof(TDestination).FullName} cannot be found when trying to map to a new instance.");
		}
		catch (Exception exc) when (_logger.WriteError(exc, new { SourceTypeName = source.GetType().FullName }))
		{
			throw new UmbrellaMappingException("There has been a problem mapping the object.", exc);
		}
	}

	/// <inheritdoc />
	public async ValueTask<TDestination> MapAsync<TSource, TDestination>(TSource source, TDestination destination, CancellationToken cancellationToken = default)
	{
		cancellationToken.ThrowIfCancellationRequested();
		Guard.IsNotNull(source);
		Guard.IsNotNull(destination);

		try
		{
			if (_registry.TryMapExistingInstanceExact(_serviceProvider, source, destination, cancellationToken, out ValueTask<TDestination> exactResult))
				return await exactResult.ConfigureAwait(false);

			throw new InvalidOperationException(
				$"A mapper implementation for the specified source type {typeof(TSource).FullName} and destination type {typeof(TDestination).FullName} cannot be found when trying to map to an existing instance.");
		}
		catch (Exception exc) when (_logger.WriteError(exc, new { SourceTypeName = source.GetType().FullName, DestinationTypeName = typeof(TDestination).FullName }))
		{
			throw new UmbrellaMappingException("There has been a problem mapping the object.", exc);
		}
	}

	/// <inheritdoc />
	public async ValueTask<IReadOnlyCollection<TDestination>> MapAllAsync<TSource, TDestination>(IEnumerable<TSource> source, CancellationToken cancellationToken = default)
	{
		cancellationToken.ThrowIfCancellationRequested();
		Guard.IsNotNull(source);

		try
		{
			if (_registry.TryMapNewCollectionExact(_serviceProvider, source, cancellationToken, out ValueTask<IReadOnlyCollection<TDestination>> exactResult))
				return await exactResult.ConfigureAwait(false);

			throw new InvalidOperationException(
				$"A mapper implementation for the specified source type {typeof(TSource).FullName} and destination type {typeof(TDestination).FullName} cannot be found when trying to map to a new collection.");
		}
		catch (Exception exc) when (_logger.WriteError(exc, new { SourceTypeName = typeof(TSource).FullName }))
		{
			throw new UmbrellaMappingException("There has been a problem mapping the object.", exc);
		}
	}
}