<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<IsTestProject>true</IsTestProject>
		<NoWarn>$(NoWarn);CA1515;CA1707</NoWarn>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\src\Umbrella.Testing.Architecture\Umbrella.Testing.Architecture.csproj" />
	</ItemGroup>

</Project>
