<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<IsPackable>false</IsPackable>
		<IsTestProject>true</IsTestProject>
		<NoWarn>$(NoWarn);CA1515;CA1707;CS1591</NoWarn>
		<UseMicrosoftTestingPlatformRunner>true</UseMicrosoftTestingPlatformRunner>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\src\Umbrella.Testing.Architecture\Umbrella.Testing.Architecture.csproj" />
	</ItemGroup>

</Project>
