<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<IsTestProject>true</IsTestProject>
		<NoWarn>$(NoWarn);CA1515;CA1707</NoWarn>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Testcontainers.Redis" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\src\Umbrella.Utilities.Threading.Redis\Umbrella.Utilities.Threading.Redis.csproj" />
	</ItemGroup>

</Project>
