using Microsoft.Extensions.DependencyInjection;

namespace Umbrella.Utilities.Mapping.Mapperly.Abstractions;

/// <summary>
/// Represents a source-generated catalog of Mapperly mappers for a single assembly or feature area.
/// </summary>
/// <remarks>
/// Implementations are intended to be generated by the <c>Umbrella.Generators.Mapperly</c> package rather than written by hand.
/// </remarks>
public interface IUmbrellaMapperlyCatalog
{
	/// <summary>
	/// Registers the mapper implementation services required by the catalog.
	/// </summary>
	/// <param name="services">The service collection.</param>
	void AddServices(IServiceCollection services);

	/// <summary>
	/// Populates the mapper registry builder with the mappings exposed by this catalog.
	/// </summary>
	/// <param name="builder">The registry builder.</param>
	void AddMappings(UmbrellaMapperRegistryBuilder builder);
}
