<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>netstandard2.0</TargetFrameworks>
	</PropertyGroup>

	<PropertyGroup>
		<PackageId>Umbrella.Xamarin</PackageId>
		<Description>This package contains various utilities and controls for use with Xamarin Forms projects.</Description>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Xamarin.CommunityToolkit" />
		<PackageReference Include="Xamarin.Essentials" />
		<PackageReference Include="Xamarin.Forms" />
	</ItemGroup>

	<ItemGroup>
		<None Include="..\..\..\icon.png" Pack="true" PackagePath="\" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\..\Core\src\Umbrella.AppFramework\Umbrella.AppFramework.csproj" />
		<ProjectReference Include="..\..\..\Core\src\Umbrella.Utilities\Umbrella.Utilities.csproj" />
		<ProjectReference Include="..\..\..\DynamicImage\src\Umbrella.DynamicImage.Abstractions\Umbrella.DynamicImage.Abstractions.csproj" />
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Update="Controls\UmbrellaActivityInidicatorView.xaml">
			<Generator>MSBuild:Compile</Generator>
		</EmbeddedResource>
	</ItemGroup>

</Project>