<Project Sdk="Microsoft.NET.Sdk.Razor">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<IsTestProject>true</IsTestProject>
		<WarningsAsErrors>$(WarningsAsErrors);RZ2012</WarningsAsErrors>
	</PropertyGroup>

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\..\Internal\src\Umbrella.Internal.Mocks\Umbrella.Internal.Mocks.csproj" />
		<ProjectReference Include="..\..\src\Umbrella.AspNetCore.Blazor\Umbrella.AspNetCore.Blazor.csproj" />
		<ProjectReference Include="..\..\src\Umbrella.AspNetCore.WebUtilities.DynamicImage\Umbrella.AspNetCore.WebUtilities.DynamicImage.csproj" />
		<ProjectReference Include="..\..\src\Umbrella.AspNetCore.WebUtilities\Umbrella.AspNetCore.WebUtilities.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Compile Include="..\Umbrella.AspNetCore.WebUtilities.Test\Mocks.cs" Link="Mocks.cs" />
		<Compile Include="..\Umbrella.AspNetCore.WebUtilities.Test\GlobalSuppressions.cs" Link="GlobalSuppressions.cs" />
	</ItemGroup>

</Project>
