namespace Umbrella.Analyzers.Test;

public class UA003_AsyncMethodCancellationAnalyzerTests : AnalyzerTestBase<AsyncMethodCancellationAnalyzer>
{
	[Theory]
	[InlineData("Task", "await Task.Yield();")]
	[InlineData("Task<int>", "await Task.Yield(); return 1;")]
	[InlineData("ValueTask", "await Task.Yield();")]
	[InlineData("ValueTask<int>", "await Task.Yield(); return 1;")]
	public async Task EligibleAsyncReturnTypeWithoutCancellationToken_ShouldTriggerDiagnostic(string returnType, string body)
	{
		string source = $"using System.Threading.Tasks; public class TestClass {{ public async {returnType} M() {{ {body} }} }}";

		await VerifyAnalyzerAsync(source, ExpectedAt(source, "M"));
	}

	[Theory]
	[InlineData("CancellationToken token = default")]
	[InlineData("CancellationToken cancellationToken")]
	[InlineData("CancellationToken cancellationToken = default(CancellationToken)")]
	[InlineData("CancellationToken cancellationToken = new()")]
	public async Task NonCanonicalCancellationTokenParameter_ShouldTriggerDiagnostic(string parameter)
	{
		string source = $"using System.Threading; using System.Threading.Tasks; public class TestClass {{ public async Task M({parameter}) {{ await Task.Yield(); }} }}";

		await VerifyAnalyzerAsync(source, ExpectedAt(source, "M"));
	}

	[Fact]
	public async Task CanonicalCancellationTokenParameter_ShouldNotTriggerDiagnostic()
	{
		const string source = "using System.Threading; using System.Threading.Tasks; public class TestClass { public async Task M(CancellationToken cancellationToken = default) { await Task.Yield(); } }";

		await VerifyNoDiagnosticsAsync(source);
	}

	[Fact]
	public async Task UnrelatedCancellationTokenType_ShouldNotSatisfyRule()
	{
		const string source = "using System.Threading.Tasks; namespace Example { public struct CancellationToken { } public class TestClass { public async Task M(CancellationToken cancellationToken = default) { await Task.Yield(); } } }";

		await VerifyAnalyzerAsync(source, ExpectedAt(source, "M"));
	}

	[Fact]
	public async Task NonPublicAndLocalMethods_ShouldNotTriggerDiagnostic()
	{
		const string source = """
			using System.Threading;
			using System.Threading.Tasks;

			public class TestClass
			{
				private async Task PrivateAsync() => await Task.Yield();
				protected async Task ProtectedAsync() => await Task.Yield();
				internal async Task InternalAsync() => await Task.Yield();

				public async Task OuterAsync(CancellationToken cancellationToken = default)
				{
					async Task LocalAsync() => await Task.Yield();
					await LocalAsync();
				}
			}
			""";

		await VerifyNoDiagnosticsAsync(source);
	}

	[Fact]
	public async Task GeneratedCode_ShouldNotTriggerDiagnostic()
	{
		const string source = """
			// <auto-generated/>
			using System.Threading.Tasks;

			public class TestClass
			{
				public async Task GeneratedAsync() => await Task.Yield();
			}
			""";

		await VerifyNoDiagnosticsAsync(source);
	}

	[Fact]
	public async Task TopLevelStatements_ShouldNotTriggerDiagnostic()
	{
		const string source = """
			using System.Threading.Tasks;
			await Task.Yield();
			""";

		await VerifyNoDiagnosticsAsync(source);
	}

	[Fact]
	public async Task Override_ShouldNotTriggerDiagnostic()
	{
		const string source = """
			using System.Threading.Tasks;

			public abstract class BaseClass
			{
				public abstract Task RunAsync();
			}

			public class TestClass : BaseClass
			{
				public override async Task RunAsync() => await Task.Yield();
			}
			""";

		await VerifyNoDiagnosticsAsync(source);
	}

	[Fact]
	public async Task InterfaceImplementations_ShouldNotTriggerDiagnostic()
	{
		const string source = """
			using System.Threading.Tasks;

			public interface IWorker
			{
				Task RunAsync();
			}

			public class ImplicitWorker : IWorker
			{
				public async Task RunAsync() => await Task.Yield();
			}

			public class ExplicitWorker : IWorker
			{
				async Task IWorker.RunAsync() => await Task.Yield();
			}
			""";

		await VerifyNoDiagnosticsAsync(source);
	}

	[Fact]
	public async Task PartialMethod_ShouldNotTriggerDiagnostic()
	{
		const string source = """
			using System.Threading.Tasks;

			public partial class TestClass
			{
				public partial Task RunAsync();

				public async partial Task RunAsync() => await Task.Yield();
			}
			""";

		await VerifyNoDiagnosticsAsync(source);
	}

	[Fact]
	public async Task DirectAndIndirectBlazorComponentMethods_ShouldNotTriggerDiagnostic()
	{
		const string source = """
			using System.Threading.Tasks;

			namespace Microsoft.AspNetCore.Components
			{
				public abstract class ComponentBase
				{
				}
			}

			public class DirectComponent : Microsoft.AspNetCore.Components.ComponentBase
			{
				public async Task SubmitFormAsync() => await Task.Yield();
				public async Task ButtonClickAsync() => await Task.Yield();
			}

			public abstract class IntermediateComponent : Microsoft.AspNetCore.Components.ComponentBase
			{
			}

			public class IndirectComponent : IntermediateComponent
			{
				public async Task UploadFileToTempDirectoryAsync() => await Task.Yield();
				public async Task UploadCallbackAsync() => await Task.Yield();
			}
			""";

		await VerifyNoDiagnosticsAsync(source);
	}

	[Fact]
	public async Task MiddlewareEntryPoint_ShouldNotTriggerDiagnostic()
	{
		const string source = """
			using System.Threading.Tasks;

			namespace Microsoft.AspNetCore.Http
			{
				public delegate Task RequestDelegate(object context);
			}

			public sealed class TestMiddleware
			{
				private readonly Microsoft.AspNetCore.Http.RequestDelegate _next;

				public TestMiddleware(Microsoft.AspNetCore.Http.RequestDelegate next)
				{
					_next = next;
				}

				public async Task InvokeAsync(object context)
				{
					await _next(context);
				}
			}
			""";

		await VerifyNoDiagnosticsAsync(source);
	}

	[Fact]
	public async Task SubmitFormMethodOutsideBlazorComponent_ShouldTriggerDiagnostic()
	{
		const string source = "using System.Threading.Tasks; public class TestClass { public async Task SubmitFormAsync() { await Task.Yield(); } }";

		await VerifyAnalyzerAsync(source, ExpectedAt(source, "SubmitFormAsync"));
	}

	[Fact]
	public async Task JSInvokableMethod_ShouldNotTriggerDiagnostic()
	{
		const string source = """
			using System;
			using System.Threading.Tasks;

			namespace Microsoft.JSInterop
			{
				[AttributeUsage(AttributeTargets.Method)]
				public sealed class JSInvokableAttribute : Attribute
				{
				}
			}

			public class TestClass
			{
				[Microsoft.JSInterop.JSInvokable]
				public async Task OpenIndustryDetailsAsync() => await Task.Yield();
			}
			""";

		await VerifyNoDiagnosticsAsync(source);
	}

	[Fact]
	public async Task TestFrameworkEntryPoints_ShouldNotTriggerDiagnostic()
	{
		const string source = """
			using System;
			using System.Threading.Tasks;

			namespace Xunit
			{
				public class FactAttribute : Attribute
				{
				}
			}

			namespace NUnit.Framework
			{
				public class TestAttribute : Attribute
				{
				}
			}

			namespace Microsoft.VisualStudio.TestTools.UnitTesting
			{
				public class TestMethodAttribute : Attribute
				{
				}
			}

			public class XunitTests
			{
				[Xunit.Fact]
				public async Task RunsAsync() => await Task.Yield();
			}

			public class NUnitTests
			{
				[NUnit.Framework.Test]
				public async Task RunsAsync() => await Task.Yield();
			}

			public class MSTestTests
			{
				[Microsoft.VisualStudio.TestTools.UnitTesting.TestMethod]
				public async Task RunsAsync() => await Task.Yield();
			}
			""";

		await VerifyNoDiagnosticsAsync(source);
	}

	[Fact]
	public async Task AttributeDerivedFromKnownTestAttribute_ShouldNotTriggerDiagnostic()
	{
		const string source = """
			using System;
			using System.Threading.Tasks;

			namespace Xunit
			{
				public class FactAttribute : Attribute
				{
				}
			}

			public sealed class CustomFactAttribute : Xunit.FactAttribute
			{
			}

			public class TestClass
			{
				[CustomFact]
				public async Task RunsAsync() => await Task.Yield();
			}
			""";

		await VerifyNoDiagnosticsAsync(source);
	}

	[Fact]
	public async Task PublicVirtualMethodWithChangeableSignature_ShouldTriggerDiagnostic()
	{
		const string source = "using System.Threading.Tasks; public class TestClass { public virtual async Task RunAsync() { await Task.Yield(); } }";

		await VerifyAnalyzerAsync(source, ExpectedAt(source, "RunAsync"));
	}

	[Fact]
	public async Task UserDefinedTaskType_ShouldNotTriggerDiagnostic()
	{
		const string source = "public class Task { } public class TestClass { public async Task RunAsync() { await System.Threading.Tasks.Task.Yield(); } }";

		await VerifyNoDiagnosticsAsync(source);
	}

	private static ExpectedDiagnostic ExpectedAt(string source, string methodName)
	{
		int column = source.IndexOf(methodName + "(", StringComparison.Ordinal) + 1;
		return Diagnostic(AsyncMethodCancellationAnalyzer.Rule, 1, column, methodName);
	}
}
