<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
		<PackageId>Umbrella.Testing.Architecture</PackageId>
		<Description>Abstract base test classes enforcing Umbrella layer dependency and implementation visibility rules using NetArchTest.Rules and xunit.v3</Description>
		<NoWarn>$(NoWarn);CA1707</NoWarn>
	</PropertyGroup>

	<ItemGroup>
		<Content Include="..\..\..\icon.png" Pack="true" PackagePath="\" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="NetArchTest.Rules" />
		<PackageReference Include="xunit.v3.assert" />
		<PackageReference Include="xunit.v3.extensibility.core" />
	</ItemGroup>

</Project>
