<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<IsTestProject>true</IsTestProject>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\..\Internal\src\Umbrella.Internal.Mocks\Umbrella.Internal.Mocks.csproj" />
		<ProjectReference Include="..\..\src\Umbrella.Utilities.Mapping.Mapperly\Umbrella.Utilities.Mapping.Mapperly.csproj" />
		<ProjectReference Include="..\..\..\Generators\src\Umbrella.Generators.Mapperly\Umbrella.Generators.Mapperly.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
	</ItemGroup>


</Project>
