namespace Umbrella.AspNetCore.Blazor.Components.DynamicImage;

/// <summary>
/// Describes a source rendered inside the picture element generated by an <see cref="UmbrellaDynamicImage"/> component.
/// </summary>
/// <param name="ContentType">The source MIME type.</param>
/// <param name="SrcSet">The responsive source set.</param>
/// <param name="Media">The optional media condition that the source applies to.</param>
public sealed record DynamicImagePictureSource(string ContentType, string SrcSet, string? Media = null);
